name: Update Docker Hub description

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Docker image name
        run: echo "image_name=${GITHUB_ACTOR}/${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_ENV

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.image_name }}
          short-description: ${{ github.event.repository.description }}
